/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedLogisticsSimulatorRouteImport } from './routes/_protected/logistics/simulator'
import { Route as ProtectedLogisticsDashboardRouteImport } from './routes/_protected/logistics/dashboard'
import { Route as ProtectedLogisticsBrandSitesIndexRouteImport } from './routes/_protected/logistics/brand-sites/index'
import { Route as ProtectedLogisticsBrandSitesCreateRouteImport } from './routes/_protected/logistics/brand-sites/create'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLogisticsSimulatorRoute =
  ProtectedLogisticsSimulatorRouteImport.update({
    id: '/logistics/simulator',
    path: '/logistics/simulator',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedLogisticsDashboardRoute =
  ProtectedLogisticsDashboardRouteImport.update({
    id: '/logistics/dashboard',
    path: '/logistics/dashboard',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedLogisticsBrandSitesIndexRoute =
  ProtectedLogisticsBrandSitesIndexRouteImport.update({
    id: '/logistics/brand-sites/',
    path: '/logistics/brand-sites/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedLogisticsBrandSitesCreateRoute =
  ProtectedLogisticsBrandSitesCreateRouteImport.update({
    id: '/logistics/brand-sites/create',
    path: '/logistics/brand-sites/create',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logistics/dashboard': typeof ProtectedLogisticsDashboardRoute
  '/logistics/simulator': typeof ProtectedLogisticsSimulatorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/logistics/brand-sites/create': typeof ProtectedLogisticsBrandSitesCreateRoute
  '/logistics/brand-sites/': typeof ProtectedLogisticsBrandSitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logistics/dashboard': typeof ProtectedLogisticsDashboardRoute
  '/logistics/simulator': typeof ProtectedLogisticsSimulatorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/logistics/brand-sites/create': typeof ProtectedLogisticsBrandSitesCreateRoute
  '/logistics/brand-sites': typeof ProtectedLogisticsBrandSitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/logistics/dashboard': typeof ProtectedLogisticsDashboardRoute
  '/_protected/logistics/simulator': typeof ProtectedLogisticsSimulatorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/logistics/brand-sites/create': typeof ProtectedLogisticsBrandSitesCreateRoute
  '/_protected/logistics/brand-sites/': typeof ProtectedLogisticsBrandSitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logistics/dashboard'
    | '/logistics/simulator'
    | '/api/auth/$'
    | '/logistics/brand-sites/create'
    | '/logistics/brand-sites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logistics/dashboard'
    | '/logistics/simulator'
    | '/api/auth/$'
    | '/logistics/brand-sites/create'
    | '/logistics/brand-sites'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/logistics/dashboard'
    | '/_protected/logistics/simulator'
    | '/api/auth/$'
    | '/_protected/logistics/brand-sites/create'
    | '/_protected/logistics/brand-sites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/logistics/simulator': {
      id: '/_protected/logistics/simulator'
      path: '/logistics/simulator'
      fullPath: '/logistics/simulator'
      preLoaderRoute: typeof ProtectedLogisticsSimulatorRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/logistics/dashboard': {
      id: '/_protected/logistics/dashboard'
      path: '/logistics/dashboard'
      fullPath: '/logistics/dashboard'
      preLoaderRoute: typeof ProtectedLogisticsDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/logistics/brand-sites/': {
      id: '/_protected/logistics/brand-sites/'
      path: '/logistics/brand-sites'
      fullPath: '/logistics/brand-sites/'
      preLoaderRoute: typeof ProtectedLogisticsBrandSitesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/logistics/brand-sites/create': {
      id: '/_protected/logistics/brand-sites/create'
      path: '/logistics/brand-sites/create'
      fullPath: '/logistics/brand-sites/create'
      preLoaderRoute: typeof ProtectedLogisticsBrandSitesCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedLogisticsDashboardRoute: typeof ProtectedLogisticsDashboardRoute
  ProtectedLogisticsSimulatorRoute: typeof ProtectedLogisticsSimulatorRoute
  ProtectedLogisticsBrandSitesCreateRoute: typeof ProtectedLogisticsBrandSitesCreateRoute
  ProtectedLogisticsBrandSitesIndexRoute: typeof ProtectedLogisticsBrandSitesIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedLogisticsDashboardRoute: ProtectedLogisticsDashboardRoute,
  ProtectedLogisticsSimulatorRoute: ProtectedLogisticsSimulatorRoute,
  ProtectedLogisticsBrandSitesCreateRoute:
    ProtectedLogisticsBrandSitesCreateRoute,
  ProtectedLogisticsBrandSitesIndexRoute:
    ProtectedLogisticsBrandSitesIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
